// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IPageController is an autogenerated mock type for the IPageController type
type IPageController struct {
	mock.Mock
}

// CreateWebPage provides a mock function with given fields: c
func (_m *IPageController) CreateWebPage(c *gin.Context) {
	_m.Called(c)
}

// GetAllWebPages provides a mock function with given fields: c
func (_m *IPageController) GetAllWebPages(c *gin.Context) {
	_m.Called(c)
}

// QueryHandle provides a mock function with given fields: c
func (_m *IPageController) QueryHandle(c *gin.Context) {
	_m.Called(c)
}

// ServerHome provides a mock function with given fields: c
func (_m *IPageController) ServerHome(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewIPageController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIPageController creates a new instance of IPageController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIPageController(t mockConstructorTestingTNewIPageController) *IPageController {
	mock := &IPageController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
