version: "3.9"
services:
  mongo-container:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./store/v1/data:/data/db
      - ./store/v1/config:/data/configdb
  
  app-container:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongo-container
