name: CI

on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name : Setting up Go 
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.19

      
      - name: building the project
        run: go build -o se.exe ./cmd/main.go

      - name: Run tests 
        run: go test -coverprofile coverage.out ./...
      
      - name: creating coverreport with codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
