name: golangci-lint
on: 
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.28.3
      - name: building the project
        run: go build -o se.exe ./cmd/main.go

      - name: Run tests 
        run: go test -coverprofile coverage.out ./...
      
      - name: creating coverreport with codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
